import fs from 'node:fs/promises';
import {IGN_LAYER,IGN_SOURCE as IGN_WMTS} from './ign-source.mjs';
import {LOCAL_IMAGERY as LOCAL_TEMPLATE} from '../dist/imagery.js';
import {createImageryCache} from './imagery-cache.mjs';
const zoom=17,x=Math.floor((4.3631+180)/360*2**zoom),y=Math.floor((1-Math.asinh(Math.tan(48.9566*Math.PI/180))/Math.PI)/2*2**zoom);
const bytes=await createImageryCache().get(zoom,x,y);
await fs.mkdir('.cache/ign',{recursive:true});await fs.writeFile('.cache/ign/centre-sample.jpg',bytes);
const meta={provider:'IGN — Géoplateforme / cartes.gouv.fr',layer:IGN_LAYER,wmts_template:IGN_WMTS,tile_matrix_set:'PM_0_19',projection:'EPSG:3857',tile_size:256,max_zoom:19,license:'Licence Ouverte / Open Licence 2.0',license_url:'https://www.etalab.gouv.fr/licence-ouverte-open-licence/',dataset:'https://cartes.gouv.fr/rechercher-une-donnee/dataset/IGNF_BD-ORTHO',acquisition_dates:'https://data.geopf.fr/annexes/ressources/fiches/photographies-aeriennes-RVB/geoportail_dates_des_prises_de_vues_aeriennes-RVB.pdf',verified_at:new Date().toISOString(),local_template:LOCAL_TEMPLATE,delivery:'Saved same-origin JPEGs are requested first, without contacting IGN from the browser. The Node acquisition service downloads a missing original once and saves it to disk before delivery. Originals are never expired or evicted. Nginx serves the shared project cache directly and forwards only missing files to the acquisition service. Static-only hosting serves saved coverage but cannot acquire new originals.',roof_projection:'Georeferenced aerial photos projected on flat roof polygons triangulated from OSM, clipped at WMTS tile boundaries. Original courtyard holes retained. No facade photography or measured roof shapes.',sample:{zoom,x,y,local:true}};
await fs.writeFile('dist/data/imagery.json',JSON.stringify(meta,null,2));console.log(JSON.stringify(meta.sample));
